export const APP_VERSION = '1.4.0';



// A short, conservative diagnostic. It measures how the learner retrieves
// Polish across different skills; it never assumes that opening a lesson means
// mastery. Questions are deliberately based on high-value family situations.
export const PLACEMENT_QUESTIONS = [
  {
    id: 'place_reading_a0', level: 'A0', skill: 'reading', type: 'choice',
    instruction: 'Choose the meaning', mainText: 'Dzień dobry.',
    options: ['Good morning / afternoon.', 'Good night.', 'See you tomorrow.'],
    answer: 'Good morning / afternoon.', itemId: 'w_dzien_dobry', weight: 1,
  },
  {
    id: 'place_guided_a0', level: 'A0', skill: 'guidedProduction', type: 'choice',
    instruction: 'Choose the natural Polish', mainText: 'Thank you very much.',
    options: ['Dziękuję bardzo.', 'Proszę bardzo.', 'Przepraszam bardzo.'],
    answer: 'Dziękuję bardzo.', weight: 1,
  },
  {
    id: 'place_listening_a1', level: 'A1', skill: 'listening', type: 'listening',
    instruction: 'Listen and choose the meaning', mainText: 'Tap to listen',
    audioText: 'Gdzie jest sklep?',
    options: ['Where is the shop?', 'How much is it?', 'When is dinner?'],
    answer: 'Where is the shop?', itemId: 'p_shop_04', weight: 1.15,
  },
  {
    id: 'place_grammar_a1', level: 'A1', skill: 'grammar', type: 'choice',
    instruction: 'Choose the missing word', mainText: 'Jadę ___ Polski.',
    options: ['do', 'w', 'na'], answer: 'do', conceptId: 'do_genitive', weight: 1.15,
  },
  {
    id: 'place_free_a1', level: 'A1', skill: 'freeProduction', type: 'typing',
    instruction: 'Write this in Polish', mainText: "I don't understand.",
    answer: 'Nie rozumiem.', acceptedAnswers: ['Nie rozumiem'], itemId: 'p_repair_01', weight: 1.2,
  },
  {
    id: 'place_reading_a1', level: 'A1', skill: 'reading', type: 'choice',
    instruction: 'Choose the meaning', mainText: 'Czy mogę w czymś pomóc?',
    options: ['Can I help with anything?', 'May I sit here?', 'Could you repeat that?'],
    answer: 'Can I help with anything?', itemId: 'p_family_02', weight: 1.15,
  },
  {
    id: 'place_guided_a1', level: 'A1', skill: 'ordering', type: 'ordering',
    instruction: 'Build the sentence', mainText: 'I live in the Netherlands.',
    answer: 'Mieszkam w Holandii', tokens: ['Mieszkam', 'w', 'Holandii'], itemId: 'p_visit_03', weight: 1.2,
  },
  {
    id: 'place_listening_a2', level: 'A2', skill: 'listening', type: 'listening',
    instruction: 'Listen and choose the meaning', mainText: 'Tap to listen',
    audioText: 'Jak minęła podróż?',
    options: ['How was the journey?', 'Where are the suitcases?', 'How long will you stay?'],
    answer: 'How was the journey?', itemId: 'p_family_03', weight: 1.35,
  },
  {
    id: 'place_free_a2', level: 'A2', skill: 'freeProduction', type: 'typing',
    instruction: 'Write a natural Polish request', mainText: 'I would like a table for two people.',
    answer: 'Chciałbym zarezerwować stolik dla dwóch osób.',
    acceptedAnswers: [
      'Chciałabym zarezerwować stolik dla dwóch osób.',
      'Poproszę stolik dla dwóch osób.',
      'Stolik dla dwóch osób, proszę.',
    ],
    itemId: 'p_rest_01', weight: 1.45,
  },
  {
    id: 'place_grammar_a2', level: 'A2', skill: 'grammar', type: 'choice',
    instruction: 'Choose the natural ending', mainText: 'Interesuję się sportami ___.',
    options: ['motorowymi', 'motorowe', 'motorowych'], answer: 'motorowymi', conceptId: 'case_instrumental', weight: 1.35,
  },
  {
    id: 'place_pronunciation', level: 'A1', skill: 'pronunciation', type: 'speaking',
    instruction: 'Read this aloud, then self-rate', mainText: 'Proszę mówić trochę wolniej.',
    audioText: 'Proszę mówić trochę wolniej.', itemId: 'p_repair_02', weight: 1.1,
  },
];

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Today', shortLabel: 'Today', icon: 'home' },
  { id: 'learn', label: 'Learn', shortLabel: 'Learn', icon: 'sparkles' },
  { id: 'review', label: 'Review', shortLabel: 'Review', icon: 'repeat', badge: 'due' },
  { id: 'talk', label: 'Talk', shortLabel: 'Talk', icon: 'message' },
  { id: 'tutor', label: 'Tutor', shortLabel: 'Tutor', icon: 'bot' },
  { id: 'games', label: 'Mini games', shortLabel: 'Games', icon: 'game' },
  { id: 'progress', label: 'Progress', shortLabel: 'Progress', icon: 'chart' },
  { id: 'library', label: 'Word library', shortLabel: 'Words', icon: 'book' },
];

export const TOPICS = [
  { id: 'greetings', title: 'Greetings', subtitle: 'Arrive warmly and naturally', emoji: '👋', priority: 100, color: 'green' },
  { id: 'family', title: 'Family gatherings', subtitle: 'Small talk that matters', emoji: '🏡', priority: 99, color: 'purple' },
  { id: 'christmas', title: 'Christmas dinner', subtitle: 'Wishes, food and traditions', emoji: '🎄', priority: 96, color: 'green' },
  { id: 'birthdays', title: 'Birthdays', subtitle: 'Wishes, gifts and celebration', emoji: '🎂', priority: 94, color: 'coral' },
  { id: 'visiting', title: 'Visiting Poland', subtitle: 'Travel, arrival and staying over', emoji: '🇵🇱', priority: 92, color: 'blue' },
  { id: 'food', title: 'Eating together', subtitle: 'Compliments and table talk', emoji: '🥟', priority: 91, color: 'amber' },
  { id: 'questions', title: 'Asking questions', subtitle: 'Keep a conversation moving', emoji: '❓', priority: 90, color: 'blue' },
  { id: 'work', title: 'Talking about work', subtitle: 'Explain what you do', emoji: '💼', priority: 84, color: 'purple' },
  { id: 'hobbies', title: 'Your hobbies', subtitle: 'Motorsport, snow, festivals, bonsai', emoji: '🏁', priority: 88, color: 'coral' },
  { id: 'weather', title: 'Weather', subtitle: 'The universal conversation opener', emoji: '🌦️', priority: 82, color: 'blue' },
  { id: 'children', title: 'Talking about children', subtitle: 'Simple, warm family questions', emoji: '🧸', priority: 80, color: 'green' },
  { id: 'shopping', title: 'Shopping', subtitle: 'Prices, quantities and payment', emoji: '🛒', priority: 81, color: 'amber' },
  { id: 'driving', title: 'Driving', subtitle: 'Directions and road talk', emoji: '🚗', priority: 77, color: 'blue' },
  { id: 'restaurant', title: 'Restaurant', subtitle: 'Order confidently and politely', emoji: '🍽️', priority: 86, color: 'coral' },
  { id: 'airport', title: 'Airport', subtitle: 'Arrival, luggage and transport', emoji: '✈️', priority: 73, color: 'blue' },
  { id: 'pharmacy', title: 'Pharmacy', subtitle: 'Ask for basic help', emoji: '💊', priority: 72, color: 'green' },
  { id: 'doctor', title: 'Doctor', subtitle: 'Describe common symptoms', emoji: '🩺', priority: 69, color: 'coral' },
  { id: 'holidays', title: 'Holidays', subtitle: 'Share plans and memories', emoji: '🏖️', priority: 70, color: 'amber' },
];

const w = (id, pl, nl, en, type, topic, frequency, example = '', level = 'A1') => ({
  id, pl, nl, en, type, topic, frequency, example, level,
});

export const WORDS = [
  w('w_byc', 'być', 'zijn', 'to be', 'verb', 'core', 1, 'Jestem z Holandii.'),
  w('w_miec', 'mieć', 'hebben', 'to have', 'verb', 'core', 2, 'Mam pytanie.'),
  w('w_robic', 'robić', 'doen / maken', 'to do / make', 'verb', 'core', 3, 'Co robisz?'),
  w('w_mowic', 'mówić', 'spreken / zeggen', 'to speak / say', 'verb', 'questions', 4, 'Mówię trochę po polsku.'),
  w('w_chciec', 'chcieć', 'willen', 'to want', 'verb', 'core', 5, 'Chcę kawę.'),
  w('w_moc', 'móc', 'kunnen / mogen', 'can / may', 'verb', 'core', 6, 'Czy mogę pomóc?'),
  w('w_wiedziec', 'wiedzieć', 'weten', 'to know a fact', 'verb', 'questions', 7, 'Nie wiem.'),
  w('w_znac', 'znać', 'kennen', 'to know / be familiar with', 'verb', 'questions', 8, 'Znam to miejsce.'),
  w('w_isc', 'iść', 'gaan (te voet)', 'to go on foot', 'verb', 'visiting', 9, 'Idę do sklepu.'),
  w('w_jechac', 'jechać', 'gaan / rijden (met vervoer)', 'to go by transport', 'verb', 'visiting', 10, 'Jadę do Polski.'),
  w('w_przyjechac', 'przyjechać', 'aankomen (met vervoer)', 'to arrive by transport', 'verb', 'visiting', 11, 'Przyjechaliśmy z Holandii.'),
  w('w_wracac', 'wracać', 'teruggaan', 'to return', 'verb', 'visiting', 12, 'Wracam jutro.'),
  w('w_jesc', 'jeść', 'eten', 'to eat', 'verb', 'food', 13, 'Jemy razem.'),
  w('w_pic', 'pić', 'drinken', 'to drink', 'verb', 'food', 14, 'Piję herbatę.'),
  w('w_lubic', 'lubić', 'leuk / lekker vinden', 'to like', 'verb', 'core', 15, 'Lubię pierogi.'),
  w('w_kochac', 'kochać', 'houden van', 'to love', 'verb', 'family', 16, 'Kocham moją rodzinę.'),
  w('w_pracowac', 'pracować', 'werken', 'to work', 'verb', 'work', 17, 'Pracuję z domu.'),
  w('w_mieszkac', 'mieszkać', 'wonen', 'to live', 'verb', 'visiting', 18, 'Mieszkam w Holandii.'),
  w('w_rozumiec', 'rozumieć', 'begrijpen', 'to understand', 'verb', 'questions', 19, 'Nie rozumiem.'),
  w('w_uczyc_sie', 'uczyć się', 'leren', 'to learn', 'verb', 'core', 20, 'Uczę się polskiego.'),
  w('w_pytac', 'pytać', 'vragen', 'to ask', 'verb', 'questions', 21, 'Chcę o coś zapytać.'),
  w('w_odpowiadac', 'odpowiadać', 'antwoorden', 'to answer', 'verb', 'questions', 22, 'Odpowiadam po polsku.'),
  w('w_pomagac', 'pomagać', 'helpen', 'to help', 'verb', 'family', 23, 'Mogę pomóc.'),
  w('w_czekac', 'czekać', 'wachten', 'to wait', 'verb', 'visiting', 24, 'Czekam na taksówkę.'),
  w('w_kupowac', 'kupować', 'kopen', 'to buy', 'verb', 'shopping', 25, 'Kupuję chleb.'),
  w('w_placic', 'płacić', 'betalen', 'to pay', 'verb', 'shopping', 26, 'Płacę kartą.'),
  w('w_szukac', 'szukać', 'zoeken', 'to look for', 'verb', 'questions', 27, 'Szukam apteki.'),
  w('w_potrzebowac', 'potrzebować', 'nodig hebben', 'to need', 'verb', 'pharmacy', 28, 'Potrzebuję pomocy.'),
  w('w_dac', 'dać', 'geven', 'to give', 'verb', 'core', 29, 'Dasz mi wodę?'),
  w('w_brac', 'brać', 'nemen', 'to take', 'verb', 'core', 30, 'Biorę kawę.'),
  w('w_widziec', 'widzieć', 'zien', 'to see', 'verb', 'core', 31, 'Miło cię widzieć.'),
  w('w_slyszec', 'słyszeć', 'horen', 'to hear', 'verb', 'core', 32, 'Dobrze cię słyszę.'),
  w('w_myslec', 'myśleć', 'denken', 'to think', 'verb', 'questions', 33, 'Myślę, że tak.'),
  w('w_czuc', 'czuć', 'voelen', 'to feel', 'verb', 'doctor', 34, 'Dobrze się czuję.'),
  w('w_pamietac', 'pamiętać', 'onthouden', 'to remember', 'verb', 'core', 35, 'Pamiętam to słowo.'),
  w('w_zapomniec', 'zapomnieć', 'vergeten', 'to forget', 'verb', 'core', 36, 'Zapomniałem słowa.'),
  w('w_spotkac', 'spotkać', 'ontmoeten', 'to meet', 'verb', 'family', 37, 'Miło was spotkać.'),
  w('w_zaczynac', 'zaczynać', 'beginnen', 'to begin', 'verb', 'core', 38, 'Zaczynamy?'),
  w('w_konczyc', 'kończyć', 'eindigen / afmaken', 'to finish', 'verb', 'core', 39, 'Kończę pracę o piątej.'),
  w('w_dzien_dobry', 'dzień dobry', 'goedendag', 'good morning / afternoon', 'expression', 'greetings', 40, 'Dzień dobry!'),
  w('w_czesc', 'cześć', 'hoi / doei', 'hi / bye', 'expression', 'greetings', 41, 'Cześć, co słychać?'),
  w('w_dziekuje', 'dziękuję', 'dank je / u', 'thank you', 'expression', 'greetings', 42, 'Dziękuję bardzo.'),
  w('w_prosze', 'proszę', 'alsjeblieft / graag gedaan', 'please / you are welcome', 'expression', 'greetings', 43, 'Proszę mówić wolniej.'),
  w('w_przepraszam', 'przepraszam', 'sorry / excuseer', 'sorry / excuse me', 'expression', 'greetings', 44, 'Przepraszam, gdzie jest sklep?'),
  w('w_tak', 'tak', 'ja', 'yes', 'adverb', 'core', 45, 'Tak, oczywiście.'),
  w('w_nie', 'nie', 'nee / niet', 'no / not', 'adverb', 'core', 46, 'Nie, dziękuję.'),
  w('w_dobrze', 'dobrze', 'goed', 'well / okay', 'adverb', 'core', 47, 'Dobrze, rozumiem.'),
  w('w_moze', 'może', 'misschien', 'maybe', 'adverb', 'core', 48, 'Może jutro.'),
  w('w_oczywiscie', 'oczywiście', 'natuurlijk', 'of course', 'adverb', 'core', 49, 'Oczywiście, mogę pomóc.'),
  w('w_kto', 'kto', 'wie', 'who', 'question', 'questions', 50, 'Kto to jest?'),
  w('w_co', 'co', 'wat', 'what', 'question', 'questions', 51, 'Co robisz?'),
  w('w_gdzie', 'gdzie', 'waar', 'where', 'question', 'questions', 52, 'Gdzie mieszkasz?'),
  w('w_kiedy', 'kiedy', 'wanneer', 'when', 'question', 'questions', 53, 'Kiedy przyjedziecie?'),
  w('w_dlaczego', 'dlaczego', 'waarom', 'why', 'question', 'questions', 54, 'Dlaczego uczysz się polskiego?'),
  w('w_jak', 'jak', 'hoe', 'how', 'question', 'questions', 55, 'Jak się masz?'),
  w('w_ile', 'ile', 'hoeveel', 'how much / many', 'question', 'shopping', 56, 'Ile to kosztuje?'),
  w('w_rodzina', 'rodzina', 'familie', 'family', 'noun', 'family', 57, 'Moja rodzina jest w Polsce.'),
  w('w_mama', 'mama', 'mama', 'mum', 'noun', 'family', 58, 'Moja mama lubi kawę.'),
  w('w_tata', 'tata', 'papa', 'dad', 'noun', 'family', 59, 'Mój tata pracuje.'),
  w('w_tesciowa', 'teściowa', 'schoonmoeder', 'mother-in-law', 'noun', 'family', 60, 'Moja teściowa gotuje obiad.'),
  w('w_tesc', 'teść', 'schoonvader', 'father-in-law', 'noun', 'family', 61, 'Mój teść lubi samochody.'),
  w('w_babcia', 'babcia', 'oma', 'grandmother', 'noun', 'family', 62, 'Jadę do babci.'),
  w('w_dziadek', 'dziadek', 'opa', 'grandfather', 'noun', 'family', 63, 'Rozmawiam z dziadkiem.'),
  w('w_zona', 'żona', 'vrouw / echtgenote', 'wife', 'noun', 'family', 64, 'Moja żona jest Polką.'),
  w('w_maz', 'mąż', 'man / echtgenoot', 'husband', 'noun', 'family', 65, 'Jej mąż pracuje w domu.'),
  w('w_corka', 'córka', 'dochter', 'daughter', 'noun', 'children', 66, 'Ich córka ma pięć lat.'),
  w('w_syn', 'syn', 'zoon', 'son', 'noun', 'children', 67, 'Nasz syn już śpi.'),
  w('w_dziecko', 'dziecko', 'kind', 'child', 'noun', 'children', 68, 'To dziecko jest bardzo miłe.'),
  w('w_dzieci', 'dzieci', 'kinderen', 'children', 'noun', 'children', 69, 'Dzieci bawią się w domu.'),
  w('w_dom', 'dom', 'huis / thuis', 'house / home', 'noun', 'family', 70, 'Wracam do domu.'),
  w('w_praca', 'praca', 'werk', 'work', 'noun', 'work', 71, 'Idę do pracy.'),
  w('w_sklep', 'sklep', 'winkel', 'shop', 'noun', 'shopping', 72, 'Gdzie jest sklep?'),
  w('w_polska', 'Polska', 'Polen', 'Poland', 'noun', 'visiting', 73, 'Jadę do Polski.'),
  w('w_holandia', 'Holandia', 'Nederland', 'the Netherlands', 'noun', 'visiting', 74, 'Jestem z Holandii.'),
  w('w_jedzenie', 'jedzenie', 'eten', 'food', 'noun', 'food', 75, 'Polskie jedzenie jest pyszne.'),
  w('w_obiad', 'obiad', 'warme maaltijd / lunch', 'main meal / lunch', 'noun', 'food', 76, 'Obiad jest gotowy.'),
  w('w_sniadanie', 'śniadanie', 'ontbijt', 'breakfast', 'noun', 'food', 77, 'Jemy śniadanie.'),
  w('w_kolacja', 'kolacja', 'avondeten', 'dinner / supper', 'noun', 'food', 78, 'Kolacja jest o siódmej.'),
  w('w_kawa', 'kawa', 'koffie', 'coffee', 'noun', 'food', 79, 'Chcesz kawy?'),
  w('w_herbata', 'herbata', 'thee', 'tea', 'noun', 'food', 80, 'Poproszę herbatę.'),
  w('w_woda', 'woda', 'water', 'water', 'noun', 'food', 81, 'Poproszę wodę.'),
  w('w_pierogi', 'pierogi', 'pierogi / Poolse dumplings', 'Polish dumplings', 'noun', 'food', 82, 'Lubię pierogi.'),
  w('w_pytanie', 'pytanie', 'vraag', 'question', 'noun', 'questions', 83, 'Mam pytanie.'),
  w('w_pomoc', 'pomoc', 'hulp', 'help', 'noun', 'questions', 84, 'Potrzebuję pomocy.'),
  w('w_czas', 'czas', 'tijd', 'time', 'noun', 'core', 85, 'Mam czas.'),
  w('w_dzisiaj', 'dzisiaj', 'vandaag', 'today', 'time', 'core', 86, 'Dzisiaj pracuję.'),
  w('w_jutro', 'jutro', 'morgen', 'tomorrow', 'time', 'core', 87, 'Do zobaczenia jutro.'),
  w('w_wczoraj', 'wczoraj', 'gisteren', 'yesterday', 'time', 'core', 88, 'Wczoraj padało.'),
  w('w_dobry', 'dobry', 'goed', 'good', 'adjective', 'core', 89, 'To dobry pomysł.'),
  w('w_mily', 'miły', 'aardig / prettig', 'nice / kind', 'adjective', 'family', 90, 'Miło cię widzieć.'),
  w('w_pyszny', 'pyszny', 'heerlijk', 'delicious', 'adjective', 'food', 91, 'Obiad jest pyszny.'),
  w('w_piekny', 'piękny', 'mooi', 'beautiful', 'adjective', 'holidays', 92, 'To piękne miejsce.'),
  w('w_zmeczony', 'zmęczony', 'moe', 'tired', 'adjective', 'core', 93, 'Jestem zmęczony.'),
  w('w_glodny', 'głodny', 'hongerig', 'hungry', 'adjective', 'food', 94, 'Jestem głodny.'),
  w('w_szczesliwy', 'szczęśliwy', 'gelukkig', 'happy', 'adjective', 'family', 95, 'Jestem szczęśliwy.'),
  w('w_cieply', 'ciepły', 'warm', 'warm', 'adjective', 'weather', 96, 'Dzisiaj jest ciepło.'),
  w('w_zimny', 'zimny', 'koud', 'cold', 'adjective', 'weather', 97, 'Woda jest zimna.'),
  w('w_trudny', 'trudny', 'moeilijk', 'difficult', 'adjective', 'core', 98, 'Polska wymowa jest trudna.'),
  w('w_latwy', 'łatwy', 'makkelijk', 'easy', 'adjective', 'core', 99, 'To pytanie jest łatwe.'),
  w('w_wolniej', 'wolniej', 'langzamer', 'more slowly', 'adverb', 'questions', 100, 'Proszę mówić wolniej.'),
  w('w_jeszcze', 'jeszcze', 'nog', 'still / more / yet', 'adverb', 'core', 101, 'Jeszcze raz, proszę.'),
  w('w_raz', 'raz', 'keer', 'time / once', 'noun', 'questions', 102, 'Jeszcze raz.'),
  w('w_razem', 'razem', 'samen', 'together', 'adverb', 'family', 103, 'Jemy razem.'),
  w('w_bardzo', 'bardzo', 'erg / zeer', 'very', 'adverb', 'core', 104, 'Bardzo dziękuję.'),
  w('w_troche', 'trochę', 'een beetje', 'a little', 'adverb', 'core', 105, 'Mówię trochę po polsku.'),
  w('w_karta', 'karta', 'kaart / pinpas', 'card', 'noun', 'shopping', 106, 'Płacę kartą.'),
  w('w_rachunek', 'rachunek', 'rekening', 'bill', 'noun', 'restaurant', 107, 'Poproszę rachunek.'),
  w('w_rezerwacja', 'rezerwacja', 'reservering', 'reservation', 'noun', 'restaurant', 108, 'Mam rezerwację.'),
  w('w_lewo', 'lewo', 'links', 'left', 'direction', 'driving', 109, 'Skręć w lewo.'),
  w('w_prawo', 'prawo', 'rechts', 'right', 'direction', 'driving', 110, 'Skręć w prawo.'),
  w('w_prosto', 'prosto', 'rechtdoor', 'straight ahead', 'direction', 'driving', 111, 'Proszę jechać prosto.'),
  w('w_apteka', 'apteka', 'apotheek', 'pharmacy', 'noun', 'pharmacy', 112, 'Gdzie jest apteka?'),
  w('w_glowa', 'głowa', 'hoofd', 'head', 'noun', 'doctor', 113, 'Boli mnie głowa.'),
  w('w_gardlo', 'gardło', 'keel', 'throat', 'noun', 'doctor', 114, 'Boli mnie gardło.'),
  w('w_pogoda', 'pogoda', 'weer', 'weather', 'noun', 'weather', 115, 'Jaka jest pogoda?'),
  w('w_deszcz', 'deszcz', 'regen', 'rain', 'noun', 'weather', 116, 'Pada deszcz.'),
  w('w_slonce', 'słońce', 'zon', 'sun', 'noun', 'weather', 117, 'Świeci słońce.'),
  w('w_samochod', 'samochód', 'auto', 'car', 'noun', 'driving', 118, 'Samochód jest przed domem.'),
  w('w_snowboard', 'snowboard', 'snowboard', 'snowboard', 'noun', 'hobbies', 119, 'Jeżdżę na snowboardzie.'),
  w('w_wyscigi', 'wyścigi', 'races / autosport', 'racing', 'noun', 'hobbies', 120, 'Lubię wyścigi samochodowe.'),
  w('w_festiwal', 'festiwal', 'festival', 'festival', 'noun', 'hobbies', 121, 'Jedziemy na festiwal.'),
  w('w_bonsai', 'bonsai', 'bonsai', 'bonsai', 'noun', 'hobbies', 122, 'Zajmuję się bonsai.'),
];

const p = (id, pl, nl, en, topic, priority, grammar = [], words = [], level = 'A1', noteNl = '', noteEn = '') => ({
  id, pl, nl, en, topic, priority, grammar, words, level, noteNl, noteEn,
});

export const PHRASES = [
  p('p_greet_01', 'Dzień dobry, miło cię widzieć.', 'Goedendag, leuk je te zien.', 'Good morning, nice to see you.', 'greetings', 100, ['pronoun_drop'], ['w_dzien_dobry','w_mily','w_widziec'], 'A0'),
  p('p_greet_02', 'Cześć, co słychać?', 'Hoi, hoe is het?', "Hi, what's new?", 'greetings', 100, [], ['w_czesc','w_co'], 'A0'),
  p('p_greet_03', 'Jak się masz?', 'Hoe gaat het met je?', 'How are you?', 'greetings', 99, ['reflexive'], ['w_jak'], 'A0'),
  p('p_greet_04', 'Bardzo dobrze, dziękuję. A ty?', 'Heel goed, dank je. En jij?', 'Very well, thank you. And you?', 'greetings', 99, ['pronoun_drop'], ['w_bardzo','w_dobrze','w_dziekuje'], 'A0'),
  p('p_greet_05', 'Dziękuję za zaproszenie.', 'Bedankt voor de uitnodiging.', 'Thank you for the invitation.', 'greetings', 97, ['case_instrumental'], ['w_dziekuje'], 'A1'),
  p('p_greet_06', 'Do zobaczenia jutro.', 'Tot morgen.', 'See you tomorrow.', 'greetings', 96, ['case_genitive'], ['w_jutro'], 'A0'),
  p('p_repair_01', 'Proszę mówić wolniej.', 'Spreek alstublieft langzamer.', 'Please speak more slowly.', 'questions', 100, ['formal_polite'], ['w_prosze','w_mowic','w_wolniej'], 'A0'),
  p('p_repair_02', 'Możesz powtórzyć?', 'Kun je dat herhalen?', 'Can you repeat that?', 'questions', 100, ['modal_infinitive'], ['w_moc'], 'A0'),
  p('p_repair_03', 'Jeszcze raz, proszę.', 'Nog een keer, alsjeblieft.', 'One more time, please.', 'questions', 99, [], ['w_jeszcze','w_raz','w_prosze'], 'A0'),
  p('p_repair_04', 'Nie rozumiem jeszcze wszystkiego.', 'Ik begrijp nog niet alles.', "I don't understand everything yet.", 'questions', 99, ['negation'], ['w_nie','w_rozumiec','w_jeszcze'], 'A0'),
  p('p_repair_05', 'Jak to się mówi po polsku?', 'Hoe zeg je dit in het Pools?', 'How do you say this in Polish?', 'questions', 98, ['reflexive','language_adverb'], ['w_jak','w_mowic'], 'A1'),
  p('p_repair_06', 'Nie znam tego słowa.', 'Ik ken dit woord niet.', "I don't know this word.", 'questions', 96, ['case_genitive','negation'], ['w_nie','w_znac'], 'A1'),
  p('p_family_01', 'Bardzo się cieszę, że tu jestem.', 'Ik ben heel blij dat ik hier ben.', "I'm very happy to be here.", 'family', 98, ['reflexive','byc_present'], ['w_bardzo','w_szczesliwy','w_byc'], 'A1'),
  p('p_family_02', 'Czy mogę w czymś pomóc?', 'Kan ik ergens mee helpen?', 'Can I help with anything?', 'family', 99, ['modal_infinitive','case_instrumental'], ['w_moc','w_pomagac'], 'A1'),
  p('p_family_03', 'Jak minęła podróż?', 'Hoe was de reis?', 'How was the journey?', 'visiting', 96, ['past_tense'], ['w_jak'], 'A1'),
  p('p_family_04', 'Podróż była długa, ale spokojna.', 'De reis was lang, maar rustig.', 'The journey was long, but calm.', 'visiting', 91, ['past_tense','gender'], ['w_byc'], 'A1'),
  p('p_family_05', 'Czuj się jak u siebie.', 'Voel je thuis.', 'Make yourself at home.', 'family', 90, ['imperative','reflexive'], ['w_czuc','w_dom'], 'A1'),
  p('p_family_06', 'Jak się wszyscy mają?', 'Hoe gaat het met iedereen?', 'How is everyone?', 'family', 92, ['reflexive'], ['w_jak','w_miec'], 'A1'),
  p('p_food_01', 'Smacznego!', 'Eet smakelijk!', 'Enjoy your meal!', 'food', 100, ['case_genitive'], [], 'A0'),
  p('p_food_02', 'To jest naprawdę pyszne.', 'Dit is echt heerlijk.', 'This is really delicious.', 'food', 100, ['gender'], ['w_byc','w_pyszny'], 'A0'),
  p('p_food_03', 'Poproszę jeszcze trochę.', 'Graag nog een beetje.', 'I would like a little more.', 'food', 97, ['polite_future'], ['w_prosze','w_jeszcze','w_troche'], 'A1'),
  p('p_food_04', 'Chcesz kawy czy herbaty?', 'Wil je koffie of thee?', 'Would you like coffee or tea?', 'food', 96, ['case_genitive'], ['w_chciec','w_kawa','w_herbata'], 'A1'),
  p('p_food_05', 'Tak, chętnie. Dziękuję.', 'Ja, graag. Dank je.', 'Yes, gladly. Thank you.', 'food', 96, [], ['w_tak','w_dziekuje'], 'A0'),
  p('p_food_06', 'Nie, dziękuję. Już wystarczy.', 'Nee, dank je. Het is genoeg.', 'No, thank you. That is enough.', 'food', 91, ['negation'], ['w_nie','w_dziekuje'], 'A1'),
  p('p_bday_01', 'Wszystkiego najlepszego!', 'Van harte gefeliciteerd!', 'Best wishes / Happy birthday!', 'birthdays', 100, ['case_genitive'], [], 'A0'),
  p('p_bday_02', 'Sto lat!', 'Lang zal je leven!', 'May you live a hundred years!', 'birthdays', 100, [], [], 'A0'),
  p('p_bday_03', 'Dziękuję za prezent.', 'Bedankt voor het cadeau.', 'Thank you for the present.', 'birthdays', 96, ['case_accusative'], ['w_dziekuje'], 'A1'),
  p('p_xmas_01', 'Wesołych Świąt!', 'Vrolijk kerstfeest!', 'Merry Christmas!', 'christmas', 100, ['case_genitive'], [], 'A0'),
  p('p_xmas_02', 'Dziękuję, nawzajem!', 'Dank je, hetzelfde!', 'Thank you, same to you!', 'christmas', 97, [], ['w_dziekuje'], 'A0'),
  p('p_xmas_03', 'Bardzo lubię polskie tradycje.', 'Ik vind Poolse tradities erg leuk.', 'I really like Polish traditions.', 'christmas', 92, ['case_accusative','adjective_agreement'], ['w_bardzo','w_lubic'], 'A1'),
  p('p_work_01', 'Pracuję w branży technologicznej.', 'Ik werk in de technologiesector.', 'I work in the technology sector.', 'work', 89, ['case_locative','pronoun_drop'], ['w_pracowac'], 'A1'),
  p('p_work_02', 'Dzisiaj pracuję z domu.', 'Vandaag werk ik thuis.', "Today I'm working from home.", 'work', 92, ['case_genitive','pronoun_drop'], ['w_dzisiaj','w_pracowac','w_dom'], 'A1'),
  p('p_work_03', 'A czym ty się zajmujesz?', 'En wat doe jij voor werk?', 'And what do you do?', 'work', 88, ['case_instrumental','reflexive'], ['w_co','w_robic'], 'A1'),
  p('p_hobby_01', 'Interesuję się sportami motorowymi.', 'Ik ben geïnteresseerd in motorsport.', "I'm interested in motorsport.", 'hobbies', 96, ['case_instrumental','pronoun_drop'], ['w_wyscigi'], 'A1'),
  p('p_hobby_02', 'W wolnym czasie jeżdżę na snowboardzie.', 'In mijn vrije tijd snowboard ik.', 'In my free time I snowboard.', 'hobbies', 94, ['case_locative','motion'], ['w_snowboard'], 'A1'),
  p('p_hobby_03', 'Lubię festiwale muzyczne.', 'Ik houd van muziekfestivals.', 'I like music festivals.', 'hobbies', 92, ['case_accusative','adjective_agreement'], ['w_lubic','w_festiwal'], 'A1'),
  p('p_hobby_04', 'Zajmuję się bonsai.', 'Ik houd me bezig met bonsai.', 'I grow and care for bonsai.', 'hobbies', 95, ['case_instrumental','reflexive'], ['w_bonsai'], 'A1'),
  p('p_weather_01', 'Jaka jest dziś pogoda?', 'Wat voor weer is het vandaag?', "What's the weather like today?", 'weather', 95, ['gender'], ['w_dzisiaj','w_pogoda'], 'A1'),
  p('p_weather_02', 'Jest zimno, ale słonecznie.', 'Het is koud, maar zonnig.', "It's cold but sunny.", 'weather', 95, ['weather_adverbs','pronoun_drop'], ['w_byc','w_zimny','w_slonce'], 'A1'),
  p('p_children_01', 'Czy dzieci już śpią?', 'Slapen de kinderen al?', 'Are the children asleep already?', 'children', 87, ['plural'], ['w_dzieci'], 'A1'),
  p('p_children_02', 'Ale szybko rosną!', 'Wat groeien ze snel!', 'They grow so quickly!', 'children', 83, ['plural','pronoun_drop'], [], 'A1'),
  p('p_shop_01', 'Ile to kosztuje?', 'Hoeveel kost dit?', 'How much does this cost?', 'shopping', 100, ['question_words'], ['w_ile'], 'A0'),
  p('p_shop_02', 'Poproszę to.', 'Deze graag.', 'I would like this.', 'shopping', 97, ['polite_future'], ['w_prosze'], 'A0'),
  p('p_shop_03', 'Czy można płacić kartą?', 'Kan ik met de kaart betalen?', 'Can I pay by card?', 'shopping', 99, ['impersonal_modal','case_instrumental'], ['w_moc','w_placic','w_karta'], 'A1'),
  p('p_shop_04', 'Gdzie jest najbliższy sklep?', 'Waar is de dichtstbijzijnde winkel?', 'Where is the nearest shop?', 'shopping', 94, ['case_nominative','adjective_agreement'], ['w_gdzie','w_sklep'], 'A1'),
  p('p_rest_01', 'Chciałbym zarezerwować stolik dla dwóch osób.', 'Ik zou een tafel voor twee personen willen reserveren.', 'I would like to reserve a table for two.', 'restaurant', 96, ['conditional_polite','case_genitive'], ['w_chciec','w_rezerwacja'], 'A2'),
  p('p_rest_02', 'Poproszę pierogi i wodę.', 'Graag pierogi en water.', 'Pierogi and water, please.', 'restaurant', 100, ['polite_future','case_accusative'], ['w_prosze','w_pierogi','w_woda'], 'A0'),
  p('p_rest_03', 'Czy mogę prosić o rachunek?', 'Mag ik om de rekening vragen?', 'Could I ask for the bill?', 'restaurant', 100, ['modal_infinitive','case_accusative'], ['w_moc','w_prosze','w_rachunek'], 'A1'),
  p('p_drive_01', 'Proszę jechać prosto.', 'Rijd alstublieft rechtdoor.', 'Please drive straight ahead.', 'driving', 95, ['formal_polite','motion'], ['w_prosze','w_jechac','w_prosto'], 'A1'),
  p('p_drive_02', 'Proszę skręcić w lewo.', 'Sla alstublieft linksaf.', 'Please turn left.', 'driving', 94, ['formal_polite','case_accusative'], ['w_prosze','w_lewo'], 'A1'),
  p('p_drive_03', 'Tutaj może pan się zatrzymać.', 'U kunt hier stoppen.', 'You can stop here.', 'driving', 91, ['formal_pan_pani','reflexive'], ['w_moc'], 'A1'),
  p('p_visit_01', 'Jutro jadę do Polski.', 'Morgen ga ik naar Polen.', "Tomorrow I'm going to Poland.", 'visiting', 100, ['motion','do_genitive'], ['w_jutro','w_jechac','w_polska'], 'A1'),
  p('p_visit_02', 'Przyjechaliśmy z Holandii.', 'We zijn uit Nederland gekomen.', 'We arrived from the Netherlands.', 'visiting', 96, ['past_tense','case_genitive'], ['w_przyjechac','w_holandia'], 'A1'),
  p('p_visit_03', 'Mieszkam w Holandii.', 'Ik woon in Nederland.', 'I live in the Netherlands.', 'visiting', 98, ['case_locative','pronoun_drop'], ['w_mieszkac','w_holandia'], 'A0'),
  p('p_air_01', 'Mam rezerwację.', 'Ik heb een reservering.', 'I have a reservation.', 'airport', 95, ['case_accusative','pronoun_drop'], ['w_miec','w_rezerwacja'], 'A0'),
  p('p_air_02', 'Gdzie jest wyjście?', 'Waar is de uitgang?', 'Where is the exit?', 'airport', 94, ['question_words'], ['w_gdzie'], 'A0'),
  p('p_air_03', 'Gdzie mogę odebrać bagaż?', 'Waar kan ik mijn bagage ophalen?', 'Where can I collect my luggage?', 'airport', 88, ['modal_infinitive'], ['w_gdzie','w_moc'], 'A1'),
  p('p_pharm_01', 'Potrzebuję czegoś na ból głowy.', 'Ik heb iets tegen hoofdpijn nodig.', 'I need something for a headache.', 'pharmacy', 94, ['case_genitive','case_accusative'], ['w_potrzebowac','w_glowa'], 'A1'),
  p('p_pharm_02', 'Mam alergię na penicylinę.', 'Ik ben allergisch voor penicilline.', "I'm allergic to penicillin.", 'pharmacy', 90, ['case_accusative'], ['w_miec'], 'A1'),
  p('p_doc_01', 'Źle się czuję.', 'Ik voel me niet goed.', "I don't feel well.", 'doctor', 98, ['reflexive'], ['w_czuc'], 'A0'),
  p('p_doc_02', 'Boli mnie gardło.', 'Ik heb keelpijn.', 'My throat hurts.', 'doctor', 96, ['body_pain_pattern'], ['w_gardlo'], 'A1'),
  p('p_doc_03', 'Boli mnie głowa od wczoraj.', 'Ik heb sinds gisteren hoofdpijn.', "I've had a headache since yesterday.", 'doctor', 95, ['body_pain_pattern','case_genitive'], ['w_glowa','w_wczoraj'], 'A1'),
  p('p_holiday_01', 'Jedziemy na wakacje do Polski.', 'We gaan op vakantie naar Polen.', "We're going on holiday to Poland.", 'holidays', 91, ['motion','do_genitive'], ['w_jechac','w_polska'], 'A1'),
  p('p_holiday_02', 'Było naprawdę pięknie.', 'Het was echt prachtig.', 'It was really beautiful.', 'holidays', 88, ['past_tense','gender'], ['w_byc','w_piekny'], 'A1'),
];

export const GRAMMAR_CONCEPTS = [
  {
    id: 'pronoun_drop', title: 'Polish often drops “I / you”', level: 'A1', priority: 100,
    visual: ['(Ja)', 'pracuję', 'dzisiaj'],
    nl: 'Net als in het Spaans zit de persoon al in de werkwoordsvorm. In het Nederlands moet je “ik” meestal zeggen; in het Pools klinkt “ja” vaak extra nadrukkelijk.',
    en: 'The verb ending already identifies the person. English needs “I”, while Polish usually omits it unless contrast or emphasis matters.',
    examples: [
      { pl: 'Pracuję z domu.', nl: 'Ik werk thuis.', en: 'I work from home.' },
      { pl: 'Ja pracuję, a on odpoczywa.', nl: 'Ík werk, en hij rust.', en: 'I am working, while he rests.' },
    ],
    mistakes: ['Ja pracuję z domu is correct, but neutral Polish prefers Pracuję z domu.'],
  },
  {
    id: 'byc_present', title: 'The verb być — to be / zijn', level: 'A1', priority: 100,
    visual: ['jestem', 'jesteś', 'jest'],
    nl: 'Pools vervoegt “zijn” sterk: jestem, jesteś, jest. Anders dan Nederlands staat het onderwerp vaak niet erbij.',
    en: 'Polish conjugates “to be” as jestem, jesteś, jest. The subject pronoun is commonly omitted.',
    examples: [
      { pl: 'Jestem z Holandii.', nl: 'Ik kom uit Nederland.', en: 'I am from the Netherlands.' },
      { pl: 'Jesteś głodny?', nl: 'Heb je honger?', en: 'Are you hungry?' },
    ],
    mistakes: ['For age, say Mam trzydzieści lat — literally “I have thirty years”, not Jestem trzydzieści.'],
  },
  {
    id: 'gender', title: 'Gender changes endings', level: 'A1', priority: 98,
    visual: ['dobry', 'dobra', 'dobre'],
    nl: 'Nederlands heeft de/het, maar bijvoeglijke naamwoorden veranderen nauwelijks. In het Pools past het einde zich aan het woordgeslacht aan.',
    en: 'Polish adjectives agree with noun gender. English adjectives never change, so this is a new signal to notice.',
    examples: [
      { pl: 'dobry obiad · dobra kawa · dobre jedzenie', nl: 'goede maaltijd · goede koffie · goed eten', en: 'good meal · good coffee · good food' },
    ],
    mistakes: ['Kawa is feminine: dobra kawa, not dobry kawa.'],
  },
  {
    id: 'do_genitive', title: 'do + genitive means “to / into”', level: 'A1', priority: 99,
    visual: ['do', 'Polsk-i', 'do Polski'],
    nl: 'Zie “do” als een richtingpijl naar binnen. Het woord erna verandert: Polska → Polski, sklep → sklepu, babcia → babci.',
    en: 'Treat do as an inward destination arrow. It requires the genitive: Polska → Polski, sklep → sklepu, babcia → babci.',
    examples: [
      { pl: 'Jadę do Polski.', nl: 'Ik ga naar Polen.', en: "I'm going to Poland." },
      { pl: 'Idę do sklepu.', nl: 'Ik ga naar de winkel.', en: "I'm going to the shop." },
      { pl: 'Jedziemy do babci.', nl: 'We gaan naar oma.', en: "We're going to grandma's." },
    ],
    mistakes: ['Not do Polska. The destination form is do Polski.'],
  },
  {
    id: 'motion', title: 'iść vs jechać: how are you moving?', level: 'A1', priority: 100,
    visual: ['🚶 iść', '→', '🚗 jechać'],
    nl: 'Het Nederlandse “gaan” splitst in twee veelgebruikte werkwoorden: iść te voet, jechać met vervoer. Kies eerst de beweging, dan de bestemming.',
    en: 'English “go” splits into iść for going on foot and jechać for going by transport.',
    examples: [
      { pl: 'Idę do pracy.', nl: 'Ik ga naar mijn werk (lopend).', en: "I'm going to work on foot." },
      { pl: 'Jadę do Polski.', nl: 'Ik ga naar Polen (met vervoer).', en: "I'm going to Poland by transport." },
    ],
    mistakes: ['For a trip from the Netherlands to Poland, Jadę do Polski is natural; Idę suggests walking.'],
  },
  {
    id: 'case_accusative', title: 'The useful object case', level: 'A1', priority: 96,
    visual: ['lubię', 'kawa → kawę'],
    nl: 'Na werkwoorden als lubić, mieć en chcieć staat het directe object vaak in de accusatief. Vrouwelijke -a wordt meestal -ę.',
    en: 'After verbs such as lubić, mieć and chcieć, the direct object often takes the accusative. Feminine -a usually becomes -ę.',
    examples: [
      { pl: 'Lubię kawę.', nl: 'Ik houd van koffie.', en: 'I like coffee.' },
      { pl: 'Mam rezerwację.', nl: 'Ik heb een reservering.', en: 'I have a reservation.' },
    ],
    mistakes: ['Lubię kawa is a common learner error; use Lubię kawę.'],
  },
  {
    id: 'case_instrumental', title: 'Instrumental after “interesować się”', level: 'A1', priority: 84,
    visual: ['interesuję się', 'sport → sportem'],
    nl: 'Bij “zich interesseren voor” gebruikt Pools een vorm die letterlijk meer op “met” lijkt: interesuję się sportem.',
    en: 'The phrase interesować się governs the instrumental case: interesuję się sportem.',
    examples: [
      { pl: 'Interesuję się sportami motorowymi.', nl: 'Ik ben geïnteresseerd in motorsport.', en: "I'm interested in motorsport." },
      { pl: 'Zajmuję się bonsai.', nl: 'Ik houd me bezig met bonsai.', en: 'I care for bonsai.' },
    ],
    mistakes: ['Do not translate the preposition word-for-word; learn the whole frame: interesować się + instrumental.'],
  },
  {
    id: 'formal_pan_pani', title: 'Pan / Pani for polite conversation', level: 'A1', priority: 90,
    visual: ['pan = u (m)', 'pani = u (v)'],
    nl: 'Pools gebruikt pan/pani plus de derde persoon. Dat lijkt op “meneer/mevrouw” maar functioneert dagelijks als beleefd “u”.',
    en: 'Polish uses pan/pani with third-person verb forms for polite “you”.',
    examples: [
      { pl: 'Czy może pan pomóc?', nl: 'Kunt u helpen? (tegen een man)', en: 'Can you help? (to a man)' },
      { pl: 'Czy może pani powtórzyć?', nl: 'Kunt u dat herhalen? (tegen een vrouw)', en: 'Can you repeat that? (to a woman)' },
    ],
    mistakes: ['Use możesz with family/friends; może pan/pani with strangers or formal situations.'],
  },
  {
    id: 'body_pain_pattern', title: 'Boli mnie… — saying what hurts', level: 'A1', priority: 74,
    visual: ['boli', 'mnie', 'gardło'],
    nl: 'Pools zegt letterlijk “de keel doet mij pijn”: boli mnie gardło. Het lichaamsdeel is grammaticaal het onderwerp.',
    en: 'Polish literally says “the throat hurts me”: boli mnie gardło. The body part is the grammatical subject.',
    examples: [
      { pl: 'Boli mnie głowa.', nl: 'Ik heb hoofdpijn.', en: 'My head hurts.' },
      { pl: 'Boli mnie gardło.', nl: 'Ik heb keelpijn.', en: 'My throat hurts.' },
    ],
    mistakes: ['Do not build this from English “I have…”; memorize boli mnie + body part.'],
  },
  {
    id: 'weather_adverbs', title: 'Weather uses adverb-like forms', level: 'A1', priority: 77,
    visual: ['zimny → zimno', 'ciepły → ciepło'],
    nl: 'Voor algemeen weer gebruikt Pools vaak een onpersoonlijke vorm: jest zimno, jest ciepło. Niet *pogoda jest zimna* in gewone smalltalk.',
    en: 'General weather descriptions use impersonal forms: jest zimno, jest ciepło.',
    examples: [
      { pl: 'Dzisiaj jest ciepło.', nl: 'Vandaag is het warm.', en: "It's warm today." },
      { pl: 'Jest zimno, ale słonecznie.', nl: 'Het is koud, maar zonnig.', en: "It's cold but sunny." },
    ],
    mistakes: ['Use jest zimno for “it is cold”; zimny describes a masculine noun such as zimny napój.'],
  },
  {
    id: 'reflexive', title: 'Small word, big pattern: się', level: 'A1', priority: 96,
    visual: ['czuć → czuć się', 'zajmować → zajmować się'],
    nl: 'Het woord się hoort bij veel Poolse werkwoorden en hoeft niet letterlijk “zich” te betekenen. Leer het hele blok: czuć się, zajmować się, interesować się.',
    en: 'The particle się belongs to many Polish verb frames and is not always a literal “oneself”. Learn the whole chunk: czuć się, zajmować się, interesować się.',
    examples: [
      { pl: 'Jak się masz?', nl: 'Hoe gaat het met je?', en: 'How are you?' },
      { pl: 'Zajmuję się bonsai.', nl: 'Ik houd me bezig met bonsai.', en: 'I care for bonsai.' },
    ],
    mistakes: ['Do not remove się just because Dutch or English uses no reflexive word in the translation.'],
  },
  {
    id: 'case_genitive', title: 'Genitive: source, absence and “some”', level: 'A1', priority: 95,
    visual: ['z Holandii', 'od wczoraj', 'nie znam słowa'],
    nl: 'De genitief verschijnt na vaste voorzetsels zoals z, do en od, vaak na ontkenning en bij een onbepaalde hoeveelheid. Leer eerst de veelgebruikte blokken.',
    en: 'The genitive appears after prepositions such as z, do and od, often after negation, and for an indefinite amount. Start with high-value chunks.',
    examples: [
      { pl: 'Przyjechaliśmy z Holandii.', nl: 'We zijn uit Nederland gekomen.', en: 'We arrived from the Netherlands.' },
      { pl: 'Chcesz kawy?', nl: 'Wil je koffie?', en: 'Would you like some coffee?' },
      { pl: 'Nie znam tego słowa.', nl: 'Ik ken dit woord niet.', en: "I don't know this word." },
    ],
    mistakes: ['The genitive has several jobs; do not force one Dutch or English preposition onto every use.'],
  },
  {
    id: 'formal_polite', title: 'Proszę + infinitive: a polite instruction', level: 'A1', priority: 92,
    visual: ['proszę', '+', 'mówić / jechać / skręcić'],
    nl: 'Proszę met een infinitief is een normale beleefde instructie: proszę mówić wolniej. Het klinkt zachter dan een kale gebiedende wijs.',
    en: 'Proszę plus an infinitive gives a normal polite instruction: proszę mówić wolniej. It is softer than a bare command.',
    examples: [
      { pl: 'Proszę mówić wolniej.', nl: 'Spreek alstublieft langzamer.', en: 'Please speak more slowly.' },
      { pl: 'Proszę jechać prosto.', nl: 'Rijd alstublieft rechtdoor.', en: 'Please drive straight ahead.' },
    ],
    mistakes: ['After proszę in this pattern, keep the second verb in the infinitive.'],
  },
  {
    id: 'modal_infinitive', title: 'Modal verb + infinitive', level: 'A1', priority: 97,
    visual: ['mogę', '+', 'pomóc / prosić / odebrać'],
    nl: 'Net als in het Nederlands draagt het modale werkwoord de persoonsvorm en blijft het tweede werkwoord infinitief: mogę pomóc.',
    en: 'As in English, the modal carries person and tense while the second verb stays infinitive: mogę pomóc.',
    examples: [
      { pl: 'Czy mogę pomóc?', nl: 'Kan ik helpen?', en: 'Can I help?' },
      { pl: 'Możesz powtórzyć?', nl: 'Kun je dat herhalen?', en: 'Can you repeat that?' },
    ],
    mistakes: ['Do not conjugate both verbs: use mogę pomóc, not *mogę pomagam.'],
  },
  {
    id: 'negation', title: 'Put nie directly before the verb', level: 'A1', priority: 96,
    visual: ['rozumiem → nie rozumiem'],
    nl: 'De basisontkenning is eenvoudig: nie staat direct voor het vervoegde werkwoord. Let later op dat het object na ontkenning vaak genitief wordt.',
    en: 'Basic negation is direct: nie goes before the conjugated verb. Later, notice that a direct object often shifts to the genitive under negation.',
    examples: [
      { pl: 'Nie rozumiem.', nl: 'Ik begrijp het niet.', en: "I don't understand." },
      { pl: 'Nie znam tego słowa.', nl: 'Ik ken dit woord niet.', en: "I don't know this word." },
    ],
    mistakes: ['Keep nie with the verb; Polish does not use a separate do/does auxiliary.'],
  },
  {
    id: 'language_adverb', title: 'Speaking “in Polish”: po polsku', level: 'A1', priority: 88,
    visual: ['po', '+', 'polsku'],
    nl: 'Voor talen gebruikt Pools vaak po + een speciale vorm: po polsku, po angielsku, po niderlandzku. Leer dit als één blok.',
    en: 'For languages, Polish often uses po plus a special form: po polsku, po angielsku, po niderlandzku. Learn it as a chunk.',
    examples: [
      { pl: 'Mówię trochę po polsku.', nl: 'Ik spreek een beetje Pools.', en: 'I speak a little Polish.' },
      { pl: 'Jak to się mówi po polsku?', nl: 'Hoe zeg je dit in het Pools?', en: 'How do you say this in Polish?' },
    ],
    mistakes: ['Say po polsku, not *w polski when you mean the language used for speaking.'],
  },
  {
    id: 'past_tense', title: 'Past tense shows gender and person', level: 'A1', priority: 91,
    visual: ['był', 'była', 'było', 'byliśmy'],
    nl: 'In de Poolse verleden tijd zie je vaak geslacht en persoon in de uitgang. Nederlands en Engels geven die informatie niet in “was/went”.',
    en: 'Polish past-tense endings often reveal gender and person. Dutch and English do not encode that information in “was/went”.',
    examples: [
      { pl: 'Podróż była spokojna.', nl: 'De reis was rustig.', en: 'The journey was calm.' },
      { pl: 'Byłem zmęczony.', nl: 'Ik was moe. (man)', en: 'I was tired. (male speaker)' },
      { pl: 'Przyjechaliśmy wczoraj.', nl: 'We kwamen gisteren aan.', en: 'We arrived yesterday.' },
    ],
    mistakes: ['A male speaker says byłem; a female speaker says byłam.'],
  },
  {
    id: 'imperative', title: 'Direct but friendly imperatives', level: 'A1', priority: 76,
    visual: ['czujesz → czuj', 'mówisz → mów'],
    nl: 'De gebiedende wijs is normaal bij familie, vooral in warme vaste uitdrukkingen. Voeg proszę toe of gebruik proszę + infinitief als je beleefder wilt klinken.',
    en: 'Imperatives are normal with family, especially in warm fixed expressions. Add proszę or use proszę + infinitive for more distance.',
    examples: [
      { pl: 'Czuj się jak u siebie.', nl: 'Voel je thuis.', en: 'Make yourself at home.' },
      { pl: 'Spróbuj pierogów.', nl: 'Proef de pierogi.', en: 'Try the pierogi.' },
    ],
    mistakes: ['Keep the reflexive particle in commands such as czuj się.'],
  },
  {
    id: 'polite_future', title: 'Poproszę: the everyday “I’d like”', level: 'A1', priority: 99,
    visual: ['poproszę', '≈', 'graag / I’d like'],
    nl: 'Poproszę is grammaticaal een toekomstige/perfectieve vorm van prosić, maar in winkels en restaurants betekent het gewoon beleefd “graag”.',
    en: 'Poproszę is grammatically a future/perfective form of prosić, but in shops and restaurants it functions as the everyday polite “I’d like”.',
    examples: [
      { pl: 'Poproszę kawę.', nl: 'Graag koffie.', en: "I'd like a coffee." },
      { pl: 'Poproszę rachunek.', nl: 'De rekening graag.', en: 'The bill, please.' },
    ],
    mistakes: ['The ordered item still takes the form required as an object: kawa → kawę.'],
  },
  {
    id: 'adjective_agreement', title: 'Adjectives copy noun signals', level: 'A1', priority: 89,
    visual: ['polski', 'polska', 'polskie'],
    nl: 'Een Pools bijvoeglijk naamwoord past zich aan geslacht, getal en naamval aan. Kijk eerst naar het zelfstandig naamwoord en kopieer de grammaticale signalen.',
    en: 'A Polish adjective agrees with its noun in gender, number, and case. Identify the noun first, then match its grammatical signals.',
    examples: [
      { pl: 'polskie tradycje', nl: 'Poolse tradities', en: 'Polish traditions' },
      { pl: 'najbliższy sklep', nl: 'de dichtstbijzijnde winkel', en: 'the nearest shop' },
    ],
    mistakes: ['Do not memorize one universal adjective ending; the noun controls the ending.'],
  },
  {
    id: 'case_locative', title: 'Locative after w and na', level: 'A1', priority: 87,
    visual: ['w Polsce', 'w Holandii', 'na snowboardzie'],
    nl: 'Bij statische locaties gebruiken w en na vaak de locatief. Daarom veranderen Polska → Polsce en Holandia → Holandii.',
    en: 'For static locations, w and na commonly take the locative. That is why Polska becomes Polsce and Holandia becomes Holandii.',
    examples: [
      { pl: 'Mieszkam w Holandii.', nl: 'Ik woon in Nederland.', en: 'I live in the Netherlands.' },
      { pl: 'Jeżdżę na snowboardzie.', nl: 'Ik snowboard.', en: 'I snowboard.' },
    ],
    mistakes: ['Movement toward a destination may use a different case: w Polsce means “in Poland”, do Polski means “to Poland”.'],
  },
  {
    id: 'plural', title: 'Plural subjects change the verb', level: 'A1', priority: 79,
    visual: ['dziecko śpi', 'dzieci śpią'],
    nl: 'Een meervoudig onderwerp krijgt een meervoudige werkwoordsvorm. Pools kan daarbij extra informatie over persoonsgroepen markeren, maar begin met de hoorbare uitgang.',
    en: 'A plural subject takes a plural verb form. Polish later distinguishes types of plural groups, but start by noticing the audible ending.',
    examples: [
      { pl: 'Dzieci już śpią.', nl: 'De kinderen slapen al.', en: 'The children are already asleep.' },
      { pl: 'Dzieci szybko rosną.', nl: 'Kinderen groeien snel.', en: 'Children grow quickly.' },
    ],
    mistakes: ['Do not pair a plural subject with the singular form śpi.'],
  },
  {
    id: 'question_words', title: 'Question word first, normal verb after it', level: 'A1', priority: 94,
    visual: ['gdzie?', 'ile?', 'jak?', 'co?'],
    nl: 'Poolse vraagwoorden lijken functioneel op Nederlandse en Engelse, maar Pools heeft meestal geen extra do/does en minder verplichte inversie.',
    en: 'Polish question words work much like English ones, but Polish has no do/does auxiliary and usually needs less inversion.',
    examples: [
      { pl: 'Gdzie jest wyjście?', nl: 'Waar is de uitgang?', en: 'Where is the exit?' },
      { pl: 'Ile to kosztuje?', nl: 'Hoeveel kost dit?', en: 'How much does this cost?' },
    ],
    mistakes: ['Do not add an English-style auxiliary: Gdzie mieszkasz? is complete.'],
  },
  {
    id: 'impersonal_modal', title: 'Można: “one can / is it possible?”', level: 'A1', priority: 90,
    visual: ['czy', 'można', 'płacić?'],
    nl: 'Można drukt algemene mogelijkheid of toestemming uit zonder “ik/jij”. Dat is ideaal voor beleefde vragen aan onbekenden.',
    en: 'Można expresses general possibility or permission without naming “I/you”, which makes it useful for polite public questions.',
    examples: [
      { pl: 'Czy można płacić kartą?', nl: 'Kan ik met de kaart betalen?', en: 'Can one pay by card?' },
      { pl: 'Można tutaj usiąść?', nl: 'Mag je hier zitten?', en: 'Is it possible to sit here?' },
    ],
    mistakes: ['Keep the following verb infinitive: można płacić, not *można płacę.'],
  },
  {
    id: 'case_nominative', title: 'Nominative: the subject and dictionary form', level: 'A1', priority: 73,
    visual: ['sklep', 'jest', 'otwarty'],
    nl: 'De nominatief is meestal de woordenboekvorm en markeert vaak wie of wat de zin bestuurt. Bij zijn-zinnen blijven onderwerp en beschrijving erop afgestemd.',
    en: 'The nominative is usually the dictionary form and often marks the subject. In “to be” sentences, the subject controls agreement.',
    examples: [
      { pl: 'Gdzie jest najbliższy sklep?', nl: 'Waar is de dichtstbijzijnde winkel?', en: 'Where is the nearest shop?' },
      { pl: 'Sklep jest otwarty.', nl: 'De winkel is open.', en: 'The shop is open.' },
    ],
    mistakes: ['A preposition or verb may trigger another case; nominative is not the default for every noun in a sentence.'],
  },
  {
    id: 'conditional_polite', title: 'Chciałbym / chciałabym: a softer request', level: 'A2', priority: 82,
    visual: ['chciałbym ♂', 'chciałabym ♀'],
    nl: 'Deze voorwaardelijke vorm maakt een wens beleefd: “ik zou graag willen”. De uitgang laat het geslacht van de spreker zien.',
    en: 'This conditional form softens a wish to “I would like”. The ending marks the speaker’s gender.',
    examples: [
      { pl: 'Chciałbym zarezerwować stolik.', nl: 'Ik zou graag een tafel reserveren. (man)', en: 'I would like to reserve a table. (male speaker)' },
      { pl: 'Chciałabym zamówić kawę.', nl: 'Ik zou graag koffie bestellen. (vrouw)', en: 'I would like to order coffee. (female speaker)' },
    ],
    mistakes: ['A male speaker uses chciałbym; a female speaker uses chciałabym.'],
  },
];

export const PATTERNS = [
  {
    id: 'pattern_go_to', topic: 'visiting', title: 'Going somewhere', subtitle: 'Movement + destination', grammar: ['motion','do_genitive'],
    template: '{motion} do {destination}.',
    default: { motion: 'Jadę', destination: 'Polski' },
    slots: {
      motion: [
        { value: 'Idę', hint: 'on foot', nl: 'ik ga lopend', en: 'I go on foot' },
        { value: 'Jadę', hint: 'by transport', nl: 'ik ga met vervoer', en: 'I go by transport' },
        { value: 'Jedziemy', hint: 'we, by transport', nl: 'wij gaan met vervoer', en: 'we go by transport' },
      ],
      destination: [
        { value: 'pracy', source: 'praca', nl: 'naar het werk', en: 'to work' },
        { value: 'sklepu', source: 'sklep', nl: 'naar de winkel', en: 'to the shop' },
        { value: 'babci', source: 'babcia', nl: 'naar oma', en: "to grandma's" },
        { value: 'Polski', source: 'Polska', nl: 'naar Polen', en: 'to Poland' },
        { value: 'domu', source: 'dom', nl: 'naar huis', en: 'home' },
      ],
    },
    noteNl: 'Lopend = iść. Met auto, trein of vliegtuig = jechać. Na do komt de genitief.',
    noteEn: 'Use iść on foot and jechać with transport. A destination after do takes the genitive.',
  },
  {
    id: 'pattern_like', topic: 'food', title: 'Saying what you like', subtitle: 'lubię + useful object', grammar: ['case_accusative'],
    template: 'Lubię {object}.',
    default: { object: 'pierogi' },
    slots: {
      object: [
        { value: 'pierogi', source: 'pierogi', nl: 'pierogi', en: 'pierogi' },
        { value: 'kawę', source: 'kawa', nl: 'koffie', en: 'coffee' },
        { value: 'polskie jedzenie', source: 'polskie jedzenie', nl: 'Pools eten', en: 'Polish food' },
        { value: 'festiwale muzyczne', source: 'festiwale muzyczne', nl: 'muziekfestivals', en: 'music festivals' },
        { value: 'wyścigi samochodowe', source: 'wyścigi samochodowe', nl: 'autosport', en: 'motor racing' },
      ],
    },
    noteNl: 'Na lubię komt het object vaak in de accusatief: kawa → kawę.',
    noteEn: 'The object after lubię is usually accusative: kawa → kawę.',
  },
  {
    id: 'pattern_can_i', topic: 'questions', title: 'Polite initiative', subtitle: 'Ask before acting', grammar: ['modal_infinitive'],
    template: 'Czy mogę {action}?',
    default: { action: 'pomóc' },
    slots: {
      action: [
        { value: 'pomóc', nl: 'helpen', en: 'help' },
        { value: 'usiąść', nl: 'gaan zitten', en: 'sit down' },
        { value: 'zapytać', nl: 'iets vragen', en: 'ask' },
        { value: 'zapłacić kartą', nl: 'met de kaart betalen', en: 'pay by card' },
        { value: 'prosić o rachunek', nl: 'om de rekening vragen', en: 'ask for the bill' },
      ],
    },
    noteNl: 'Na mogę volgt de infinitief, net als na “kan/mag ik” in het Nederlands.',
    noteEn: 'The infinitive follows mogę, similar to “can I + verb” in English.',
  },
  {
    id: 'pattern_interests', topic: 'hobbies', title: 'Talking about interests', subtitle: 'A high-value family topic', grammar: ['case_instrumental'],
    template: 'Interesuję się {interest}.',
    default: { interest: 'sportami motorowymi' },
    slots: {
      interest: [
        { value: 'sportami motorowymi', nl: 'motorsport', en: 'motorsport' },
        { value: 'muzyką', nl: 'muziek', en: 'music' },
        { value: 'fotografią', nl: 'fotografie', en: 'photography' },
        { value: 'polską kulturą', nl: 'Poolse cultuur', en: 'Polish culture' },
        { value: 'bonsai', nl: 'bonsai', en: 'bonsai' },
      ],
    },
    noteNl: 'Leer de hele combinatie: interesować się + instrumentalis.',
    noteEn: 'Learn the full frame: interesować się + instrumental.',
  },
  {
    id: 'pattern_pain', topic: 'doctor', title: 'Describing pain', subtitle: 'Useful at a doctor or pharmacy', grammar: ['body_pain_pattern'],
    template: 'Boli mnie {body}.',
    default: { body: 'głowa' },
    slots: {
      body: [
        { value: 'głowa', nl: 'mijn hoofd doet pijn', en: 'my head hurts' },
        { value: 'gardło', nl: 'mijn keel doet pijn', en: 'my throat hurts' },
        { value: 'brzuch', nl: 'mijn buik doet pijn', en: 'my stomach hurts' },
        { value: 'ucho', nl: 'mijn oor doet pijn', en: 'my ear hurts' },
      ],
    },
    noteNl: 'Letterlijk: “het hoofd doet mij pijn”. Daarom is het boli, niet mam.',
    noteEn: 'Literally: “the head hurts me”. This is why Polish uses boli rather than mam.',
  },
];

export const REAL_LIFE_SCENARIOS = [
  { id: 'scenario_arrival', topic: 'visiting', title: 'Arriving at the family home', emoji: '🏡', minutes: 8, phrases: ['p_greet_01','p_family_01','p_family_02','p_family_03','p_family_04'] },
  { id: 'scenario_christmas', topic: 'christmas', title: 'Christmas dinner', emoji: '🎄', minutes: 10, phrases: ['p_xmas_01','p_xmas_02','p_food_01','p_food_02','p_food_03'] },
  { id: 'scenario_birthday', topic: 'birthdays', title: 'A family birthday', emoji: '🎂', minutes: 7, phrases: ['p_bday_01','p_bday_02','p_bday_03','p_food_05'] },
  { id: 'scenario_table', topic: 'food', title: 'Eating together', emoji: '🥟', minutes: 9, phrases: ['p_food_01','p_food_02','p_food_03','p_food_04','p_food_05','p_food_06'] },
  { id: 'scenario_restaurant', topic: 'restaurant', title: 'Ordering at a restaurant', emoji: '🍽️', minutes: 9, phrases: ['p_rest_01','p_rest_02','p_rest_03','p_shop_03'] },
  { id: 'scenario_groceries', topic: 'shopping', title: 'Buying groceries', emoji: '🛒', minutes: 8, phrases: ['p_shop_01','p_shop_02','p_shop_03','p_shop_04'] },
  { id: 'scenario_directions', topic: 'driving', title: 'Giving a taxi driver directions', emoji: '🚕', minutes: 8, phrases: ['p_drive_01','p_drive_02','p_drive_03'] },
  { id: 'scenario_airport', topic: 'airport', title: 'At the airport', emoji: '✈️', minutes: 8, phrases: ['p_air_01','p_air_02','p_air_03','p_repair_01'] },
  { id: 'scenario_pharmacy', topic: 'pharmacy', title: 'At a pharmacy', emoji: '💊', minutes: 9, phrases: ['p_pharm_01','p_pharm_02','p_doc_01'] },
  { id: 'scenario_doctor', topic: 'doctor', title: 'A basic doctor visit', emoji: '🩺', minutes: 10, phrases: ['p_doc_01','p_doc_02','p_doc_03','p_repair_01'] },
  { id: 'scenario_holidays', topic: 'holidays', title: 'Talking about holidays', emoji: '🏖️', minutes: 8, phrases: ['p_holiday_01','p_holiday_02','p_weather_01'] },
  { id: 'scenario_hobbies', topic: 'hobbies', title: 'Explaining your hobbies', emoji: '🏁', minutes: 9, phrases: ['p_hobby_01','p_hobby_02','p_hobby_03','p_hobby_04'] },
];

export const PERSONAS = [
  { id: 'mother-in-law', name: 'Mother-in-law', polishRole: 'teściowa', nlRole: 'schoonmoeder', emoji: '👩', scenario: 'Welcoming you at home', topic: 'family', level: 'Warm & supportive' },
  { id: 'father-in-law', name: 'Father-in-law', polishRole: 'teść', nlRole: 'schoonvader', emoji: '👨', scenario: 'Work and hobbies', topic: 'hobbies', level: 'Relaxed small talk' },
  { id: 'grandmother', name: 'Grandmother', polishRole: 'babcia', nlRole: 'oma', emoji: '👵', scenario: 'Christmas dinner', topic: 'christmas', level: 'Slow & affectionate' },
  { id: 'waiter', name: 'Waiter', polishRole: 'kelner', nlRole: 'ober', emoji: '🧑‍🍳', scenario: 'Ordering dinner', topic: 'restaurant', level: 'Natural service Polish' },
  { id: 'cashier', name: 'Cashier', polishRole: 'kasjerka', nlRole: 'kassière', emoji: '👩‍💼', scenario: 'Buying groceries', topic: 'shopping', level: 'Quick everyday Polish' },
  { id: 'neighbour', name: 'Neighbour', polishRole: 'sąsiadka', nlRole: 'buurvrouw', emoji: '🧑', scenario: 'Weather and local chat', topic: 'weather', level: 'Friendly small talk' },
  { id: 'taxi-driver', name: 'Taxi driver', polishRole: 'taksówkarz', nlRole: 'taxichauffeur', emoji: '🚕', scenario: 'Getting to the family home', topic: 'driving', level: 'Practical & direct' },
];

export const CONVERSATIONS = {
  'mother-in-law': {
    scenarioTitle: 'You have just arrived at the family home in Poland.',
    turns: [
      {
        role: 'Cześć, Kars! Jak minęła podróż?',
        nl: 'Hoi Kars! Hoe was de reis?',
        en: 'Hi Kars! How was the journey?',
        suggestions: [
          { pl: 'Dobrze, dziękuję. Podróż była spokojna.', intent: ['dobrze','dziękuję','podróż','spokojna'] },
          { pl: 'Trochę długo, ale wszystko dobrze.', intent: ['długo','dobrze'] },
          { pl: 'Byłem zmęczony, ale cieszę się, że tu jestem.', intent: ['zmęczony','cieszę','jestem'] },
        ],
        coach: 'Use była because podróż is feminine. Dutch and English do not mark this on “was”.',
      },
      {
        role: 'Chcesz kawy czy herbaty?',
        nl: 'Wil je koffie of thee?',
        en: 'Would you like coffee or tea?',
        suggestions: [
          { pl: 'Poproszę kawę, dziękuję.', intent: ['kawę','dziękuję'] },
          { pl: 'Herbatę, proszę.', intent: ['herbatę','proszę'] },
          { pl: 'Nie, dziękuję. Może później.', intent: ['nie','dziękuję','później'] },
        ],
        coach: 'After poproszę, feminine kawa changes to kawę and herbata to herbatę.',
      },
      {
        role: 'Obiad będzie za pół godziny. Jesteś głodny?',
        nl: 'Het eten is over een half uur klaar. Heb je honger?',
        en: 'Dinner will be ready in half an hour. Are you hungry?',
        suggestions: [
          { pl: 'Tak, bardzo. Mogę w czymś pomóc?', intent: ['tak','bardzo','pomóc'] },
          { pl: 'Trochę. Czy mogę nakryć do stołu?', intent: ['trochę','mogę'] },
        ],
        coach: 'For a male speaker use głodny; a female speaker says głodna.',
      },
      {
        role: 'Oczywiście. Możesz położyć talerze na stole.',
        nl: 'Natuurlijk. Je kunt de borden op tafel zetten.',
        en: 'Of course. You can put the plates on the table.',
        suggestions: [
          { pl: 'Jasne. Gdzie są talerze?', intent: ['jasne','gdzie','talerze'] },
          { pl: 'Dobrze, już pomagam.', intent: ['dobrze','pomagam'] },
        ],
        coach: 'Jasne is a natural, friendly “sure”. It is common in family speech.',
      },
    ],
  },
  'father-in-law': {
    scenarioTitle: 'You are having coffee and talking about work and hobbies.',
    turns: [
      {
        role: 'Czym się zajmujesz w Holandii?',
        nl: 'Wat doe je voor werk in Nederland?',
        en: 'What do you do in the Netherlands?',
        suggestions: [
          { pl: 'Pracuję w branży technologicznej.', intent: ['pracuję','branży'] },
          { pl: 'Pracuję z domu i dużo rozmawiam z ludźmi.', intent: ['pracuję','domu','ludźmi'] },
        ],
        coach: 'Learn Czym się zajmujesz? as one natural chunk for “What do you do?”.',
      },
      {
        role: 'A co lubisz robić w wolnym czasie?',
        nl: 'En wat doe je graag in je vrije tijd?',
        en: 'What do you like doing in your free time?',
        suggestions: [
          { pl: 'Interesuję się sportami motorowymi.', intent: ['interesuję','sportami','motorowymi'] },
          { pl: 'Jeżdżę na snowboardzie i lubię festiwale.', intent: ['snowboardzie','festiwale'] },
          { pl: 'Zajmuję się bonsai.', intent: ['bonsai'] },
        ],
        coach: 'Interesuję się requires the instrumental: sport → sportem, sporty → sportami.',
      },
      {
        role: 'Naprawdę? Ja też lubię wyścigi. Formuła 1 czy rajdy?',
        nl: 'Echt? Ik houd ook van races. Formule 1 of rally?',
        en: 'Really? I like racing too. Formula 1 or rally?',
        suggestions: [
          { pl: 'Najbardziej lubię Formułę 1.', intent: ['formułę','1'] },
          { pl: 'Lubię oba, ale częściej oglądam Formułę 1.', intent: ['oba','formułę'] },
        ],
        coach: 'Formuła changes to Formułę after lubię, just like kawa → kawę.',
      },
    ],
  },
  grandmother: {
    scenarioTitle: 'Christmas dinner with grandmother. She speaks slowly and warmly.',
    turns: [
      {
        role: 'Kars, kochanie, wesołych Świąt!',
        nl: 'Kars, lieverd, vrolijk kerstfeest!',
        en: 'Kars, dear, Merry Christmas!',
        suggestions: [
          { pl: 'Wesołych Świąt, babciu!', intent: ['wesołych','świąt','babciu'] },
          { pl: 'Dziękuję, babciu. Nawzajem!', intent: ['dziękuję','babciu','nawzajem'] },
        ],
        coach: 'When addressing babcia directly, Polish uses the vocative babciu.',
      },
      {
        role: 'Spróbuj pierogów. Sama je zrobiłam.',
        nl: 'Proef de pierogi. Ik heb ze zelf gemaakt.',
        en: 'Try the pierogi. I made them myself.',
        suggestions: [
          { pl: 'Dziękuję. Są naprawdę pyszne!', intent: ['dziękuję','pyszne'] },
          { pl: 'Chętnie. Bardzo lubię pierogi.', intent: ['chętnie','lubię','pierogi'] },
        ],
        coach: 'Pierogi is plural, so “they are delicious” is są pyszne.',
      },
      {
        role: 'Jeszcze trochę?',
        nl: 'Nog een beetje?',
        en: 'A little more?',
        suggestions: [
          { pl: 'Tak, poproszę jeszcze trochę.', intent: ['tak','poproszę','trochę'] },
          { pl: 'Nie, dziękuję. Już wystarczy.', intent: ['nie','dziękuję','wystarczy'] },
        ],
        coach: 'Poproszę is a compact, very useful polite request—more natural than translating “I want”.',
      },
    ],
  },
  waiter: {
    scenarioTitle: 'A relaxed restaurant dinner in Kraków.',
    turns: [
      {
        role: 'Dobry wieczór. Czy mają państwo rezerwację?',
        nl: 'Goedenavond. Heeft u een reservering?',
        en: 'Good evening. Do you have a reservation?',
        suggestions: [
          { pl: 'Tak, mam rezerwację na nazwisko Kars.', intent: ['tak','rezerwację','kars'] },
          { pl: 'Nie, ale czy jest stolik dla dwóch osób?', intent: ['nie','stolik','dwóch'] },
        ],
        coach: 'Na nazwisko means “under the name”. It is useful at hotels and restaurants too.',
      },
      {
        role: 'Co podać do picia?',
        nl: 'Wat mag ik u te drinken brengen?',
        en: 'What can I get you to drink?',
        suggestions: [
          { pl: 'Poproszę wodę niegazowaną.', intent: ['wodę','niegazowaną'] },
          { pl: 'Dla mnie herbata, proszę.', intent: ['herbata','proszę'] },
        ],
        coach: 'Woda becomes wodę as the object of poproszę.',
      },
      {
        role: 'Czy są już państwo gotowi zamówić?',
        nl: 'Bent u klaar om te bestellen?',
        en: 'Are you ready to order?',
        suggestions: [
          { pl: 'Tak. Poproszę pierogi ruskie.', intent: ['tak','pierogi'] },
          { pl: 'Jeszcze chwilę, proszę.', intent: ['jeszcze','chwilę','proszę'] },
        ],
        coach: 'Jeszcze chwilę is a natural way to ask for another moment.',
      },
      {
        role: 'Czy wszystko smakowało?',
        nl: 'Heeft alles gesmaakt?',
        en: 'Did everything taste good?',
        suggestions: [
          { pl: 'Tak, było bardzo smaczne. Poproszę rachunek.', intent: ['tak','smaczne','rachunek'] },
          { pl: 'Tak, dziękuję. Czy mogę prosić o rachunek?', intent: ['dziękuję','rachunek'] },
        ],
        coach: 'Use było smaczne for the overall meal; the neuter form matches an implied jedzenie.',
      },
    ],
  },
  cashier: {
    scenarioTitle: 'A quick grocery checkout. The cashier speaks at natural speed.',
    turns: [
      {
        role: 'Dzień dobry. Czy ma pan kartę sklepu?',
        nl: 'Goedendag. Heeft u een klantenkaart?',
        en: 'Good afternoon. Do you have a store card?',
        suggestions: [
          { pl: 'Nie, nie mam.', intent: ['nie','mam'] },
          { pl: 'Tak, już pokazuję.', intent: ['tak','pokazuję'] },
        ],
        coach: 'Nie mam is enough; Polish drops the pronoun and often the repeated object.',
      },
      {
        role: 'Torba będzie potrzebna?',
        nl: 'Heeft u een tas nodig?',
        en: 'Will you need a bag?',
        suggestions: [
          { pl: 'Tak, poproszę jedną torbę.', intent: ['tak','jedną','torbę'] },
          { pl: 'Nie, dziękuję. Mam własną.', intent: ['nie','dziękuję','własną'] },
        ],
        coach: 'In fast everyday speech, Polish often omits “czy”: Torba będzie potrzebna?',
      },
      {
        role: 'Płatność kartą czy gotówką?',
        nl: 'Betaling met kaart of contant?',
        en: 'Card or cash?',
        suggestions: [
          { pl: 'Kartą, proszę.', intent: ['kartą','proszę'] },
          { pl: 'Zapłacę gotówką.', intent: ['gotówką'] },
        ],
        coach: 'Kartą is instrumental: “by means of card”. Learn płacić kartą as a whole phrase.',
      },
    ],
  },
  neighbour: {
    scenarioTitle: 'You meet a neighbour outside the family home.',
    turns: [
      {
        role: 'Dzień dobry! Przyjechał pan z Holandii?',
        nl: 'Goedendag! Bent u uit Nederland gekomen?',
        en: 'Good afternoon! Did you arrive from the Netherlands?',
        suggestions: [
          { pl: 'Tak, przyjechaliśmy wczoraj.', intent: ['tak','przyjechaliśmy','wczoraj'] },
          { pl: 'Tak. Odwiedzamy rodzinę.', intent: ['tak','rodzinę'] },
        ],
        coach: 'The neighbour uses pan for polite “you”. Replying without ja sounds natural.',
      },
      {
        role: 'Macie szczęście, dziś jest piękna pogoda.',
        nl: 'Jullie hebben geluk, vandaag is het prachtig weer.',
        en: "You're lucky, the weather is beautiful today.",
        suggestions: [
          { pl: 'Tak, jest ciepło i słonecznie.', intent: ['ciepło','słonecznie'] },
          { pl: 'Tak, lepiej niż w Holandii!', intent: ['lepiej','holandii'] },
        ],
        coach: 'For general weather, use adverb forms: ciepło, zimno, słonecznie.',
      },
      {
        role: 'Jak długo zostajecie?',
        nl: 'Hoe lang blijven jullie?',
        en: 'How long are you staying?',
        suggestions: [
          { pl: 'Zostajemy do niedzieli.', intent: ['niedzieli'] },
          { pl: 'Tylko kilka dni.', intent: ['kilka','dni'] },
        ],
        coach: 'Do + genitive also marks an endpoint in time: do niedzieli, until Sunday.',
      },
    ],
  },
  'taxi-driver': {
    scenarioTitle: 'A taxi ride from the airport to the family home.',
    turns: [
      {
        role: 'Dzień dobry. Dokąd jedziemy?',
        nl: 'Goedendag. Waar gaan we naartoe?',
        en: 'Good afternoon. Where are we going?',
        suggestions: [
          { pl: 'Dzień dobry. Na ulicę Długą, proszę.', intent: ['ulicę','proszę'] },
          { pl: 'Do centrum, proszę.', intent: ['centrum','proszę'] },
        ],
        coach: 'Dokąd asks for a destination; gdzie asks for a location.',
      },
      {
        role: 'Jechać przez centrum czy obwodnicą?',
        nl: 'Via het centrum of de ringweg?',
        en: 'Through the centre or by the ring road?',
        suggestions: [
          { pl: 'Proszę jechać najszybszą drogą.', intent: ['najszybszą','drogą'] },
          { pl: 'Przez centrum, proszę.', intent: ['centrum','proszę'] },
        ],
        coach: 'Najszybszą drogą means “by the fastest route”; drogą is instrumental.',
      },
      {
        role: 'Jesteśmy na miejscu. Tutaj?',
        nl: 'We zijn er. Hier?',
        en: "We're here. Here?",
        suggestions: [
          { pl: 'Tak, tutaj. Dziękuję bardzo.', intent: ['tak','tutaj','dziękuję'] },
          { pl: 'Trochę dalej, po prawej stronie.', intent: ['dalej','prawej'] },
        ],
        coach: 'Na miejscu is the everyday phrase for “at the destination / here”.',
      },
    ],
  },
};

export const TUTOR_TOPICS = [
  {
    id: 'count-one-ten',
    keywords: [
      'count to ten', 'count till ten', 'count to 10', 'count till 10', 'count from 1 to 10',
      'numbers one to ten', 'numbers 1 to 10', 'polish numbers', 'counting',
      'tellen tot tien', 'tellen tot 10', 'tel tot tien', 'tel tot 10', 'hoe tel ik tot tien', 'hoe tel ik tot 10', 'cijfers een tot tien', 'poolse cijfers', 'poolse getallen',
      'liczyć do dziesięciu', 'liczby od jednego do dziesięciu',
    ],
    title: 'Count from 1 to 10 in Polish',
    nl: 'Voor gewoon tellen zeg je: jeden, dwa, trzy, cztery, pięć, sześć, siedem, osiem, dziewięć, dziesięć. Eén en twee veranderen later soms mee met het geslacht van een zelfstandig naamwoord, maar voor los tellen zijn dit de juiste basisvormen.',
    en: 'For simple counting, say: jeden, dwa, trzy, cztery, pięć, sześć, siedem, osiem, dziewięć, dziesięć. One and two can later change with the gender of a noun, but these are the correct basic counting forms.',
    examples: [
      ['1 — jeden', 'één', 'one'],
      ['2 — dwa', 'twee', 'two'],
      ['3 — trzy', 'drie', 'three'],
      ['4 — cztery', 'vier', 'four'],
      ['5 — pięć', 'vijf', 'five'],
      ['6 — sześć', 'zes', 'six'],
      ['7 — siedem', 'zeven', 'seven'],
      ['8 — osiem', 'acht', 'eight'],
      ['9 — dziewięć', 'negen', 'nine'],
      ['10 — dziesięć', 'tien', 'ten'],
    ],
    exercise: { prompt: 'What comes after pięć?', answer: 'sześć', options: ['cztery', 'sześć', 'siedem'] },
  },
  {
    id: 'family-dinner-tutor',
    keywords: [
      'family dinner', 'dinner with family', 'family meal', 'christmas dinner', 'family gathering',
      'familiediner', 'eten met familie', 'kerstdiner', 'familiebijeenkomst',
      'obiad rodzinny', 'kolacja z rodziną', 'wigilia',
    ],
    title: 'A practical family-dinner mini lesson',
    nl: 'Begin met drie functies: iets aanbieden, reageren op eten en het gesprek herstellen. Daarmee kun je al meedoen zonder lange grammaticale uitleg. Gebruik krótkie, warme zinnen en stel daarna één eenvoudige vraag terug.',
    en: 'Start with three functions: offering something, reacting to food, and repairing the conversation. That lets you participate without a long grammar lesson. Use short, warm sentences and then ask one simple question back.',
    examples: [
      ['Czy mogę pomóc?', 'Kan ik helpen?', 'Can I help?'],
      ['To jest bardzo smaczne.', 'Dit is erg lekker.', 'This is very tasty.'],
      ['Poproszę trochę.', 'Graag een beetje.', "I'd like a little, please."],
      ['Możesz powtórzyć?', 'Kun je dat herhalen?', 'Can you repeat that?'],
      ['A ty, co lubisz?', 'En jij, wat vind jij lekker?', 'And you, what do you like?'],
    ],
    exercise: { prompt: 'Your mother-in-law offers more food. Choose a warm answer:', answer: 'Tak, poproszę trochę.', options: ['Tak, poproszę trochę.', 'Nie rozumiem pogody.', 'Gdzie jest samochód?'] },
  },
  {
    id: 'go-poland',
    keywords: ['do polski','do polska','going to poland','naar polen','idę do polski','jadę do polski'],
    title: 'Why “Jadę do Polski” works',
    nl: 'Gebruik jadę wanneer je met vervoer gaat. Na do komt de genitief, dus Polska verandert in Polski. Het patroon is: beweging + do + bestemming in de genitief.',
    en: 'Use jadę when travelling by transport. The preposition do takes the genitive, so Polska becomes Polski. The pattern is movement + do + destination in the genitive.',
    examples: [
      ['Jadę do Polski.', 'Ik ga naar Polen.', "I'm going to Poland."],
      ['Idę do sklepu.', 'Ik loop naar de winkel.', "I'm walking to the shop."],
      ['Jedziemy do babci.', 'We gaan naar oma.', "We're going to grandma's."],
    ],
    exercise: { prompt: 'Choose the natural sentence for a trip by car:', answer: 'Jadę do Polski.', options: ['Idę do Polska.','Jadę do Polski.','Jestem do Polski.'] },
  },
  {
    id: 'isc-jechac',
    keywords: ['iść','isc','jechać','jechac','gaan','go on foot','motion verb'],
    title: 'iść vs jechać',
    nl: 'Het Nederlandse “gaan” is te breed voor het Pools. iść = te voet; jechać = met auto, trein, fiets, bus of vliegtuig. Daarna kies je de bestemming.',
    en: 'English “go” is broader than Polish. iść means on foot; jechać means by vehicle or transport. Then add the destination.',
    examples: [
      ['Idę do pracy.', 'Ik loop naar mijn werk.', "I'm walking to work."],
      ['Jadę do pracy.', 'Ik ga met vervoer naar mijn werk.', "I'm going to work by transport."],
    ],
    exercise: { prompt: 'You are flying to Poland. Complete: ___ do Polski.', answer: 'Jadę', options: ['Idę','Jadę','Jest'] },
  },
  {
    id: 'age',
    keywords: ['age','leeftijd','years old','lat','mam lat','wiek'],
    title: 'Age uses mieć, not być',
    nl: 'Pools werkt hier zoals Frans: je “hebt” een aantal jaren. Zeg Mam trzydzieści lat, niet Jestem trzydzieści lat.',
    en: 'Polish says you “have” a number of years: Mam trzydzieści lat, not Jestem trzydzieści lat.',
    examples: [
      ['Mam trzydzieści lat.', 'Ik ben dertig jaar.', "I'm thirty years old."],
      ['Ile masz lat?', 'Hoe oud ben je?', 'How old are you?'],
    ],
    exercise: { prompt: 'Translate: “I am thirty years old.”', answer: 'Mam trzydzieści lat.', options: ['Jestem trzydzieści lat.','Mam trzydzieści lat.','Mnie trzydzieści lat.'] },
  },
  {
    id: 'pronouns',
    keywords: ['pronoun','voornaamwoord','ja jestem','drop i','omit i','onderwerp'],
    title: 'Why Polish often omits the subject',
    nl: 'De uitgang vertelt al wie het doet: pracuję = ik werk, pracujesz = jij werkt. “Ja” gebruik je vooral voor contrast of nadruk.',
    en: 'The ending already tells you who acts: pracuję = I work, pracujesz = you work. Use ja mainly for contrast or emphasis.',
    examples: [
      ['Pracuję z domu.', 'Ik werk thuis.', 'I work from home.'],
      ['Ja gotuję, a ty nakrywasz.', 'Ík kook en jij dekt de tafel.', 'I cook, while you set the table.'],
    ],
    exercise: { prompt: 'Which sounds neutral?', answer: 'Mieszkam w Holandii.', options: ['Ja mieszkam w Holandii.','Mieszkam w Holandii.'] },
  },
  {
    id: 'kawa-kawe',
    keywords: ['kawę','kawe','kawa','accusative','biernik','lubię kawę','object case'],
    title: 'Why kawa becomes kawę',
    nl: 'Kawa is vrouwelijk en eindigt op -a. Als het een direct object is na lubić, mieć, chcieć of poproszę, verandert -a meestal in -ę.',
    en: 'Kawa is feminine and ends in -a. As a direct object after lubić, mieć, chcieć or poproszę, -a usually changes to -ę.',
    examples: [
      ['Lubię kawę.', 'Ik houd van koffie.', 'I like coffee.'],
      ['Poproszę herbatę.', 'Graag thee.', 'Tea, please.'],
    ],
    exercise: { prompt: 'Complete: Poproszę ___ (kawa).', answer: 'kawę', options: ['kawa','kawę','kawy'] },
  },
  {
    id: 'pan-pani',
    keywords: ['pan','pani','formal','formeel','u zeggen','polite you'],
    title: 'Polite “you”: pan and pani',
    nl: 'Tegen onbekenden gebruik je vaak pan (man) of pani (vrouw) plus de derde persoon. Tegen familie stap je meestal over op ty zodra dat natuurlijk is.',
    en: 'With strangers, use pan for a man or pani for a woman plus third-person verb forms. Family usually uses informal ty once appropriate.',
    examples: [
      ['Czy może pan pomóc?', 'Kunt u helpen? (man)', 'Can you help? (man)'],
      ['Czy może pani powtórzyć?', 'Kunt u herhalen? (vrouw)', 'Can you repeat that? (woman)'],
    ],
    exercise: { prompt: 'Politely ask a female cashier to repeat:', answer: 'Czy może pani powtórzyć?', options: ['Możesz powtórzyć?','Czy może pani powtórzyć?','Czy pan powtórzysz?'] },
  },
  {
    id: 'pronunciation-l',
    keywords: ['ł','pronunciation','uitspraak','w sound','how pronounce l stroke'],
    title: 'The sound of Polish ł',
    nl: 'Poolse ł klinkt meestal als de Engelse w in “water”, niet als Nederlandse l. Dus mały klinkt ongeveer als “MAH-wih”.',
    en: 'Polish ł is usually like English w in “water”, not an l sound. So mały is roughly “MAH-wih”.',
    examples: [
      ['był', 'ongeveer “bihw”', 'roughly “bihw”'],
      ['mały', 'ongeveer “MAH-wih”', 'roughly “MAH-wih”'],
    ],
    exercise: { prompt: 'Which English sound is closest to Polish ł?', answer: 'w', options: ['l','w','r'] },
  },
  {
    id: 'sz-cz',
    keywords: ['sz','cz','rz','ż','pronunciation polish','poolse uitspraak'],
    title: 'A practical pronunciation map',
    nl: 'sz ≈ “sh”, cz ≈ “ch”, ż/rz ≈ de stemhebbende “zh” in het Engelse “vision”. Spreek clusters langzaam als blokken, niet letter voor letter.',
    en: 'sz is roughly “sh”, cz roughly “ch”, and ż/rz the voiced “zh” in “vision”. Learn clusters as sound blocks, not separate letters.',
    examples: [
      ['proszę', 'PRO-sheh', 'PRO-sheh'],
      ['cześć', 'cheshch', 'cheshch'],
      ['dobrze', 'DOB-zheh', 'DOB-zheh'],
    ],
    exercise: { prompt: 'Which cluster is closest to English “sh”?', answer: 'sz', options: ['cz','sz','rz'] },
  },
];

export const RESCUE_PHRASES = [
  { pl: 'Proszę mówić wolniej.', nl: 'Spreek alstublieft langzamer.', en: 'Please speak more slowly.' },
  { pl: 'Możesz powtórzyć?', nl: 'Kun je dat herhalen?', en: 'Can you repeat that?' },
  { pl: 'Nie rozumiem jeszcze wszystkiego.', nl: 'Ik begrijp nog niet alles.', en: "I don't understand everything yet." },
  { pl: 'Jak to się mówi po polsku?', nl: 'Hoe zeg je dit in het Pools?', en: 'How do you say this in Polish?' },
  { pl: 'Rozumiem trochę.', nl: 'Ik begrijp een beetje.', en: 'I understand a little.' },
];

export const GAME_TYPES = [
  { id: 'matching', title: 'Word matching', description: 'Pair Polish with meaning before the board fills your working memory.', icon: 'grid', minutes: 3, skill: 'Recognition', color: 'green' },
  { id: 'ordering', title: 'Sentence ordering', description: 'Build natural Polish word order from useful family sentences.', icon: 'shuffle', minutes: 4, skill: 'Sentence building', color: 'purple' },
  { id: 'listening', title: 'Listening quiz', description: 'Hear a phrase at natural speed and catch the message that matters.', icon: 'headphones', minutes: 4, skill: 'Listening', color: 'blue' },
  { id: 'family-challenge', title: 'Family challenge', description: 'Survive a rapid sequence of realistic family questions.', icon: 'users', minutes: 5, skill: 'Conversation', color: 'coral' },
  { id: 'rapid', title: 'Rapid vocabulary', description: 'Recall high-value words under gentle time pressure.', icon: 'bolt', minutes: 2, skill: 'Recall speed', color: 'amber' },
  { id: 'memory', title: 'Memory cards', description: 'Find pairs while the coach quietly tracks confusion patterns.', icon: 'cards', minutes: 4, skill: 'Memory', color: 'green' },
];
